id: A6591F918
title: 'The Beautiful Garland of Lotuses: A Prayer to the Lineage of the Rediscovered
  Treasure, Five-Deity Subjugative Hayagrīva'
type: translation
pechas:
- IF8C88BEA
- IFF63442B
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:14:59.198694
  last_modified_at: 2023-01-04 12:14:59.198704
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IF8C88BEA/473F: DB1D
  IFF63442B/C03D: DB1D
